### ISSUE TITLE
Include Puppet 4

### ISSUE THREAD

**Issue by martialblog** [elasticdog/puppet-sandbox#20]
I'm working on including Puppet 4. This is a working Build: 
https://github.com/martialblog/puppet-sandbox/commit/611b7901a60dcef099e06def6ccabb71d50a94af

However, there are some issues. 
- [x] The nodes.pp and site.pp are not in place yet.
- [x]  Puppet 4 seems to like a lot of memory. I couldn't get it down... 
- [ ] Would be cool to select either Puppet 3 or 4.

**Comment by martialblog** [comment]
Maybe it was my Laptop, but this configuration workes fine on different workstations. Probably needs further testing. 

https://github.com/martialblog/puppet-sandbox/commit/ebaa944c2a233717fd508ffc2e4fe9c7aeb06527

**Comment by Cinderhaze** [comment]
By default, I think puppet server uses 3G of memory, you need to manually override the JAVA_ARGS 

I was trying to do something similar with docker, but I keep running into some weird issues with permissions, I was going to go back to my old standby of this puppet-sandbox project and try it with puppetserver.  

http://grahamgilbert.com/blog/2015/06/22/running-puppet-server-in-docker/

They, for demonstration, set the parameters like this..
PUPPETSERVER_JAVA_ARGS="-Xms384m -Xmx384m -XX:MaxPermSize=256m"

I'm not sure if you are setting it up to run using the JRuby/Clojure based puppetserver, or if you are just trying to run puppetmaster using ruby.  If ruby, ignore my comment.

**Comment by martialblog** [comment]
This should basically work with Puppet 4. Needs to be properly tested however:
https://github.com/martialblog/puppet-sandbox/commit/d98c97780b6808fec89a7ac39aa0581da1078e23

No idea how to smoothly switch between Puppet 3 and 4 yet. Maybe a flexible params.pp should be enough...

**Comment by Cinderhaze** [comment]
They install with different source repos if you are using the official puppet labs repos.  I remember I stopped using the sandbox when the master was set up as 3.8 but the client was 4.x and they were incompatible.
